language: c
sudo: false
addons:
  apt:
    packages:
    - libnl-3-dev
    - libgcrypt11-dev
    - zlib1g-dev
    - libsqlite3-dev
    - libpcap-dev
    - libssl-dev
    - libnl-genl-3-dev
    - libpcre3-dev
compiler:
  - gcc
  - clang
script: make sqlite=true experimental=true && make check sqlite=true experimental=true && make clean && make sqlite=true experimental=true gcrypt=true && make check sqlite=true experimental=true gcrypt=true && make pcre=true && make check pcre=true && CFLAGS="-g -W -Wall -O0" make sqlite=true experimental=true && CFLAGS="-g -W -Wall -O0" make check sqlite=true experimental=true && make clean && CFLAGS="-g -W -Wall -O0" make sqlite=true experimental=true gcrypt=true && CFLAGS="-g -W -Wall -O0" make check sqlite=true experimental=true gcrypt=true && CFLAGS="-g -W -Wall -O0" make pcre=true && CFLAGS="-g -W -Wall -O0" make check pcre=true
